<div id="mp_admin_form" class="mp_admin_form">
	<ul class="mp_admin_fields">
		<li class="mp_admin_field_item"><label class="mp_admin_field_label">Photo</label>
			<?php if (!$worker->photo1):?>
				<input type="file" name="photo1" class="mp_admin_field_input mp_admin_field_input_file" />
			<?php else:?>
				<img src="<?php echo htmlentities($worker->get_image_url('photo1'))?>" class="mp_admin_field_input mp_admin_field_input_img" />
				<input type="file" name="photo1" class="mp_admin_field_input mp_admin_field_input_file" />
			<?php endif?>
		</li>
		<li class="mp_admin_field_item"><label class="mp_admin_field_label">First Name</label><input type="text" name="firstname" class="mp_admin_field_input" value="<?php echo htmlentities($worker->firstname, ENT_QUOTES, 'UTF-8')?>" /></li>
		<li class="mp_admin_field_item"><label class="mp_admin_field_label">Middle Name</label><input type="text" name="middlename" class="mp_admin_field_input" value="<?php echo htmlentities($worker->middlename, ENT_QUOTES, 'UTF-8')?>" /></li>
		<li class="mp_admin_field_item"><label class="mp_admin_field_label">Last Name</label><input type="text" name="lastname" class="mp_admin_field_input" value="<?php echo htmlentities($worker->lastname, ENT_QUOTES, 'UTF-8')?>" /></li>		
		<li class="mp_admin_field_item"><label class="mp_admin_field_label">Position Desired</label><input type="text" name="position_desired" class="mp_admin_field_input" value="<?php echo htmlentities($worker->position_desired, ENT_QUOTES, 'UTF-8')?>" /></li>		
		<li class="mp_admin_field_item"><label class="mp_admin_field_label">Email Address</label><input type="text" name="email" class="mp_admin_field_input" value="<?php echo htmlentities($worker->email, ENT_QUOTES, 'UTF-8')?>" /></li>		
		<li class="mp_admin_field_item"><label class="mp_admin_field_label">Telephone Number</label><input type="text" name="telephone_number" class="mp_admin_field_input" value="<?php echo htmlentities($worker->telephone_number, ENT_QUOTES, 'UTF-8')?>" /></li>		
		<li class="mp_admin_field_item"><label class="mp_admin_field_label">Birthday</label><input type="text" name="birthday" class="mp_admin_field_input" value="<?php echo htmlentities($worker->birthday, ENT_QUOTES, 'UTF-8')?>" /></li>		
		<li class="mp_admin_field_item"><label class="mp_admin_field_label">Citizenship</label><input type="text" name="citizenship" class="mp_admin_field_input" value="<?php echo htmlentities($worker->citizenship, ENT_QUOTES, 'UTF-8')?>" /></li>
		<li class="mp_admin_field_item"><label class="mp_admin_field_label">Height</label><input type="text" name="height" class="mp_admin_field_input" value="<?php echo htmlentities($worker->height, ENT_QUOTES, 'UTF-8')?>" /></li>
		<li class="mp_admin_field_item"><label class="mp_admin_field_label">Weight</label><input type="text" name="weight" class="mp_admin_field_input" value="<?php echo htmlentities($worker->weight, ENT_QUOTES, 'UTF-8')?>" /></li>
		<li class="mp_admin_field_item"><label class="mp_admin_field_label">Color of Hair</label><input type="text" name="color_of_hair" class="mp_admin_field_input" value="<?php echo htmlentities($worker->color_of_hair, ENT_QUOTES, 'UTF-8')?>" /></li>
		<li class="mp_admin_field_item"><label class="mp_admin_field_label">Color of Eyes</label><input type="text" name="color_of_eyes" class="mp_admin_field_input" value="<?php echo htmlentities($worker->color_of_eyes, ENT_QUOTES, 'UTF-8')?>" /></li>		
		<li class="mp_admin_field_item"><label class="mp_admin_field_label">Civil Status</label><input type="text" name="civil_status" class="mp_admin_field_input" value="<?php echo htmlentities($worker->civil_status, ENT_QUOTES, 'UTF-8')?>" /></li>		
		
		
		<li class="mp_admin_field_item"><label class="mp_admin_field_label">Description</label><textarea name="description" class="mp_admin_field_input"><?php echo htmlentities($worker->description, ENT_QUOTES, 'UTF-8')?></textarea></li>		
		<li class="mp_admin_field_item"><label class="mp_admin_field_label">Skills</label><textarea name="skills" class="mp_admin_field_input"><?php echo htmlentities($worker->skills, ENT_QUOTES, 'UTF-8')?></textarea></li>		
	</ul>
	<div class="mp_clear"></div>
</div>