<div id="mp_view" class="mp_view">
	<div class="mp_message"></div>
	<ul class="mp_fields">
		<li class="mp_fields">
				<img src="<?php echo htmlentities($worker->get_image_url('photo1'))?>" class="mp_field_span mp_field_span_img"/>
		</li>
		<li class="mp_field_item"><span class="mp_field_label">Position Desired</span> <span class="mp_field_value"> <?php echo htmlentities($worker->position_desired, ENT_QUOTES, 'UTF-8')?></span></li>
		<li class="mp_field_item"><span class="mp_field_label">First Name</span> <span class="mp_field_value"> <?php echo htmlentities($worker->firstname, ENT_QUOTES, 'UTF-8')?></span></li>
		<li class="mp_field_item"><span class="mp_field_label">Middle Name</span> <span class="mp_field_value"> <?php echo htmlentities($worker->middlename, ENT_QUOTES, 'UTF-8')?></span></li>				
		<li class="mp_field_item"><span class="mp_field_label">Last Name</span> <span class="mp_field_value"> <?php echo htmlentities($worker->lastname, ENT_QUOTES, 'UTF-8')?></span></li>			
		<li class="mp_field_item"><span class="mp_field_label">Birthday</span> <span class="mp_field_value"> <?php echo htmlentities($worker->birthday, ENT_QUOTES, 'UTF-8')?></span></li>		
		<li class="mp_field_item"><span class="mp_field_label">Citizenship</span> <span class="mp_field_value"> <?php echo htmlentities($worker->citizenship, ENT_QUOTES, 'UTF-8')?></span></li>		
		<li class="mp_field_item"><span class="mp_field_label">Height</span> <span class="mp_field_value"> <?php echo htmlentities($worker->height, ENT_QUOTES, 'UTF-8')?></span></li>		
		<li class="mp_field_item"><span class="mp_field_label">Weight</span> <span class="mp_field_value"> <?php echo htmlentities($worker->weight, ENT_QUOTES, 'UTF-8')?></span></li>						
		<li class="mp_field_item"><span class="mp_field_label">Color of Hair</span> <span class="mp_field_value"> <?php echo htmlentities($worker->color_of_hair, ENT_QUOTES, 'UTF-8')?></span></li>		
		<li class="mp_field_item"><span class="mp_field_label">Color of Eyes</span> <span class="mp_field_value"> <?php echo htmlentities($worker->color_of_eyes, ENT_QUOTES, 'UTF-8')?></span></li>		
		<li class="mp_field_item"><span class="mp_field_label">Civil Status</span> <span class="mp_field_value"> <?php echo htmlentities($worker->civil_status, ENT_QUOTES, 'UTF-8')?></span></li>				
		
		<li class="mp_field_item">
			<span class="mp_field_label">Description</span>
		</li>		
		<li class="mp_field_item">
			<span class="mp_field_value_block"><?php echo nl2br(htmlentities($worker->description, ENT_QUOTES, 'UTF-8'))?></span>
		</li>
		<li class="mp_field_item">
			<span class="mp_field_label">Skills</span>
		</li>
		<li class="mp_field_item">
			<span class="mp_field_value mp_field_value"> <?php echo nl2br(htmlentities($worker->skills, ENT_QUOTES, 'UTF-8'))?></span>
		</li>		
	</ul>
</div>